export const descriptions = {
	archair:
		'Un gars, une fille, une boite à rythme et l’envie de tailler la route. C’est en juin 2019 que la sédunoise Isis Lambiel et le biennois Bastien Jeandrevin sortent leur premier single « Wrong Feels Right », qui sera diffusé sur les ondes, suivi d’un EP « Roller Coaster » qui leur ouvrira la porte à une série de concerts en Suisse romande. Résolument minimaliste mais efficace, le duo assène avec conviction un rock fiévreux et bluesy sur une base de poum-clap frénétique.',
	i_bredda:
		'I-Bredda sound system c’est deux amis qui partagent la même passion pour la culture sound system roots, reggae et dub. Le projet débute en 2021 en récupérant une partie de la sono d’un ami. C’est ce qui nous permettra d’organiser plusieurs événements et de se faire la main. Menuisier et électricien de métier, nous avons eu la chance de pouvoir combiner nos connaissances afin d’améliorer constamment le sound system. Strictly vinyls on good vibes 🔥',
	kety_fusco:
		"Kety Fusco a obtenu un diplôme de harpe classique au Conservatoire en Italie à l'âge de 21 ans, et en seulement deux ans, elle a fait une tournée européenne avec son nouveau projet et son inséparable harpe électrique. Kety a développé un son unique grâce à la vision d'une nouvelle harpe, à la recherche de sons non traditionnels que l'on ne s'attendrait jamais à entendre d'une harpe. Elle travaille avec les harpes électriques Delta de Salvi Harps, qui ont choisi Kety comme ambassadrice officielle. L'exploration de la harpe et de la technologie par Kety Fusco a commencé avec son premier album à succès, DAZED (Universal distribution), décrit par les critiques suisses comme 'une race rare'. Avec DAZED, Kety a en effet choisi de ne pas suivre la tradition des harpistes qui découvrent la harpe à travers les réverbérations et les boucles classiques : elle forge une nouvelle identité artistique pour la harpe en basant sa sonorisation, par exemple, sur les sons d'un vinyle gratté sur des cordes métalliques, sur certains objets frappés sur la table d'harmonie de la harpe classique pré-échantillonnée, et sur des effets analogiques manipulés en direct. Kety Fusco a donné plus de 80 concerts dans toute l’Europe parmi les plus importants, il y a le concert pour les Nations Unies au SGD Global Festival of Action, partageant la scène virtuelle avec deux de ses idoles Patti Smith et Ben Harper, et travaille actuellement sur la première bibliothèque de sons de harpe non traditionnels suivi d'une composition de recherche contemporaine sur la harpe de musique expérimentale/ électronique composée exclusivement avec des sons de sa bibliothèque sonore.",
	maissouille:
		"Maissouille est un producteur et DJ international de Hard Music, basé en France. Créateur & propriétaire de la marque ''Hardcore France'', label et organisation ultime en France. Maissouille a commencé la production musicale en tant que pionnier du tribecore, ce qui l'a ouvert et a provoqué une grande explosion du genre musical nouvellement inventé en France - après une reconnaissance publique immédiate, Maissouille est devenu imparable ! Grâce à des compositions fracassantes sur le dancefloor et à l'énorme charisme de l'artiste, les performances de Maissouille sont pleines de dynamisme et d'interaction, de battage médiatique et d'atmosphère extraordinaire, qui ne laisse jamais le public indifférent ! Après 15 ans passés aux platines, Maissouille continue sans aucun doute à dominer la place des DJ de Hard Music en France.",
	mascarpone:
		"Mascarpone is a electronic music project created by Hugo Bussiere in 2018. His influences come mainly from old school EBM to all kind of electronic music. Moreover, movies are a fundamental aspect of Mascarpone's music and his greatest source of inspiration.",
	nathalie:
		'Le duo lausannois Nathalie Froehlich et Yanneck affectionne la musique électronique, le rap et les sports nocturnes. Membres de la Sacrée Déter, collectif organisateur de raves party et évènements culturels, le DJ et la rappeuse prépare un live énergique mélangeant Break, Bass, rythmes débiles et Hip Hop digne d’une After qu’on n’aurait pas envie de quitter. Après une release sur le label fribourgeois Strecke, le programme 2022 s’annonce bien chargée pour la rappeuse et son compagnon avec une trentaine de représentations en Suisse et son premier EP Désillusion. Merci de ne pas les nourrir après minuit, au risque de mettre en péril la société capitaliste.',
	regal_trip:
		'Natural Trance De Reims à Ibiza, en passant par Paris, l’Angleterre ou l’Autriche, Regal Trip enchaîne les concerts depuis 2008. Aujourd’hui composé de Bryan Vély à la batterie, Mathias Jamart au didgeridoo, Edouard Tranchand aux percussions et Erwan Thomas à la basse, le groupe génère un univers Trance Electro puissant, mêlant les sonorités d’instruments traditionnels d’Australie et d’Afrique de l’Ouest aux influences techno. En 2019, Regal Trip sort son troisième album, Take a Trip, sur Clé USB. Ce nouveau concept permet d’intégrer une interface graphique, ajoutant une dimension visuelle résolument originale.',
	roots_joy:
		'Roots of Joy a été crée par Joyce Dutoit en 2016, fan de reggae, roots & dub elle est rejointe par Mohammed Zouaoui en 2017 pour prendre le mic’ et ambiancer en tant que MC. Fans de reggae et rasta dans l’âme, on joue du Roots au Dub digital et on propage le message de JAH Rastafari.',
	wading_birds:
		"Deux potes du Lavaux passionnés par le mouvement Reggae, Dub, qui apprenant sur le tas et grâce à un bon nombre de coups de pouces, se sont lancés dans la fabrication d'une sono. Strictly vinyls selection !",
	magonia:
		"We Are Magonia est un groupe de musique électronique/métal composé de Fear Collins, Frank Sinistra et Louis De Funeste se sont formés en 2017. Ils sont fortement influencés par les bandes originales de films d'horreur des années 80, le baroque musique classique de l'époque et musique death / black metal. We Are Magonia délivre une musique puissante et dansante basée sur sons de synthétiseurs torturés. Le projet a été entièrement DIY depuis le début. WAM a créé presque tous les contenus qu'ils ont sortis et a géré tous les aspects du groupe (composition, production, travail en studio, artworks, promotion, montage vidéo, merch holding...). De cette façon, ils ont commencé à développer une base de fans très favorable (par exemple, 50 000 auditeurs mensuels et +7 millions de flux au total). La configuration en direct du groupe est composée des trois membres principaux, l'un joue Guitare et deux autres pièces de synthétiseurs, plus un batteur en direct. Les membres du groupe portent un visage personnalisé modélisé et imprimé en 3D des masques et des costumes de scène. Tous les membres sont expérimentés et ont tourné dans différents projets au cours des 10 dernières années avant de créer We Are Magonia. Le groupe a récemment terminé la production de son 3ème LP intitulé 'Triangle Unicode' qui attend de sortir sur New Retro Wave Records."
};
